package mirrors

type Mirror struct {
	Name       string
	Identifier string
}

var AllMirrors = []Mirror{
	{"Adoptium", "adoptium"},
	{"Alpine", "alpine"},
	{"Anaconda", "anaconda"},
	{"Anaconda Extra", "anaconda-extra"},
	{"安同 OS", "aosc"},
	{"AOSP", "aosp"},
	{"Arch Linux", "archlinux"},
	{"Arch Linux ARM", "archlinuxarm"},
	{"Arch Linux CN", "archlinuxcn"},
	{"Arch4edu", "arch4edu"},
	{"Armbian", "armbian"},
	{"CentOS", "centos"},
	{"CentOS Stream", "centos-stream"},
	{"CentOS Vault", "centos-vault"},
	{"Ceph", "ceph"},
	{"Cygwin", "cygwin"},
	{"Debian", "debian"},
	{"Deepin", "deepin"},
	{"Docker CE", "docker-ce"},
	{"ELRepo", "elrepo"},
	{"EPEL", "epel"},
	{"Fedora", "fedora"},
	{"FreeBSD", "freebsd"},
	{"Gentoo", "gentoo"},
	{"Homebrew", "homebrew"},
	{"Kali", "kali"},
	{"Kubernetes", "kubernetes"},
	{"Linux Mint", "linuxmint"},
	{"Manjaro", "manjaro"},
	{"MariaDB", "mariadb"},
	{"MongoDB", "mongodb"},
	{"MSYS2", "msys2"},
	{"MySQL", "mysql"},
	{"NixOS", "nixos"},
	{"NodeJS", "nodejs-release"},
	{"OpenBSD", "openbsd"},
	{"openSUSE", "opensuse"},
	{"OpenWRT", "openwrt"},
	{"Proxmox", "proxmox"},
	{"PyPI", "pypi"},
	{"Qt", "qt"},
	{"Raspbian", "raspbian"},
	{"Rocky Linux", "rocky"},
	{"ROS", "ros"},
	{"RPMFusion", "rpmfusion"},
	{"Ubuntu", "ubuntu"},
	{"Void Linux", "voidlinux"},
}
